"""Fixed multiplies primary_keys

Revision ID: 42e690ac3fec
Revises: 64cf8b84a9f6
Create Date: 2025-05-31 01:32:21.344693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42e690ac3fec'
down_revision: Union[str, None] = '64cf8b84a9f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'sku')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('sku', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
