"""Initial migration

Revision ID: 714be4b18ed0
Revises: 
Create Date: 2025-06-02 02:34:34.489021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '714be4b18ed0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('zoho_organization_id', sa.String(), nullable=False),
    sa.Column('ecwid_store_id', sa.BigInteger(), nullable=False),
    sa.Column('location', sa.String(), server_default='eu', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ecwid_store_id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('zoho_organization_id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('zoho_item_id', sa.String(), nullable=False),
    sa.Column('ecwid_item_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('zoho_order_id', sa.String(), nullable=False),
    sa.Column('ecwid_order_id', sa.String(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zoho_tokens',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('expires_in', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('refresh_token'),
    sa.UniqueConstraint('store_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zoho_tokens')
    op.drop_table('orders')
    op.drop_table('items')
    op.drop_table('stores')
    # ### end Alembic commands ###
