"""add expiration column to tokens

Revision ID: b7127f8ce09c
Revises: e693970361b0
Create Date: 2025-05-30 20:10:10.885034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7127f8ce09c'
down_revision: Union[str, None] = 'e693970361b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zoho_tokens', sa.Column('expires_in', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zoho_tokens', 'expires_in')
    # ### end Alembic commands ###
