"""add location column to stores

Revision ID: ef303e38c87b
Revises: 75b880c2ffda
Create Date: 2025-05-23 01:14:56.039625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef303e38c87b'
down_revision: Union[str, None] = '75b880c2ffda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('location', sa.String(), server_default='eu', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'location')
    # ### end Alembic commands ###
